export const ADD_ARTICLE = 'ADD_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const ADD_COMMENT ='ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const TOGGLE_UNSAFE_MODE = 'TOGGLE_UNSAFE_MODE';